### ISSUE TITLE
Icon not setting correctly

### ISSUE THREAD

**Issue by PhanaticD** [Bimmr/BimmCore#5]
the icon for a map is being set to:
      Icon: !!me.bimmr.bimmcore.items.Items {}

**Comment by PhanaticD** [comment]
I tried manually setting it to an item, and now it is a random item every time the server starts for some reason

**Comment by PhanaticD** [comment]
I think it may be the ! 

```
    Carnival:
      Spawns:
        Zombies:
        - infection,-900,100,-121,-351.22607,0.44996625
        - infection,-863,100,-128,-0.0692749,-2.250044
        - infection,-810,95,-106,-326.9118,-6.6000576
        - infection,-809,96,-26,-54.0495,0.5999396
        - infection,-810,97,59,-220.69836,5.2499433
        - infection,-899,100,79,-163.10004,4.349905
        - infection,-974,99,67,-176.58508,5.249909
        - infection,-988,100,-1,-94.68298,1.0498947
        - infection,-830,96,-36,-235.8617,1.7997878
        Humans:
        - infection,-902,100,-19,-321.68628,3.1500258
        - infection,-896,100,8,-224.48907,7.200032
        - infection,-970,100,25,-124.58917,3.4500594
        - infection,-973,100,-22,-69.681335,4.6500573
        - infection,-893,100,-89,-73.72717,4.500038
      Creator: Build Team
      Description:
      - Survive the Carnival
      - until the time is up!
    Icon: item:66
```
